import {IconType} from "../iconType";

export const DeliveryTruckCargoRegular: IconType = {
    name: 'delivery-truck-cargo',
    key: 'DeliveryTruckCargo',
    type: 'regular',
    width: 24,
    height: 24,
    viewBox: '0 0 24 24',
    svgPathData: [{"name":"circle","attributes":{"cx":"18.75","cy":"18.75","r":"1.5","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"circle","attributes":{"cx":"5.25","cy":"18.75","r":"1.5","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M20.25 18.75h1.5a1.5 1.5 0 0 0 1.5-1.5v-6a3 3 0 0 0-3-3H16.5","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M16.5 18.75V5.25a1.5 1.5 0 0 0-1.5-1.5H2.25a1.5 1.5 0 0 0-1.5 1.5v12a1.5 1.5 0 0 0 1.5 1.5h1.5","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M17.25 18.75H6.75","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M23.25 12.75H21a1.5 1.5 0 0 1-1.5-1.5v-3","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M.75 11.25h12V15","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M5.25 6.75h6v4.5h-6z","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M3.75 11.25v2.25","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M8.25 6.75V9","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M9.75 11.25v2.25","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M6.75 11.25V15","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]}],
}
