import {IconType} from "../iconType";

export const SeasonWinterRegular: IconType = {
    name: 'season-winter',
    key: 'SeasonWinter',
    type: 'regular',
    width: 24,
    height: 24,
    viewBox: '0 0 24 24',
    svgPathData: [{"name":"path","attributes":{"d":"M14.58 20.38s1.22 2.5 3.27 2.31c4.16-.38 3.88-5.91 5.4-7.86a9.1 9.1 0 0 0-8.27.08c-2.15 1.22-2.31 3.27-.41 5.48z","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M17.52 17.84s-2.7.34-4.62 5.03","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M9.75 1.13v18","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M18.75 10.13h-18","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"m7.5 12.38-2.89 2.89","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M14.89 4.98 12 7.88","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"m4.61 4.98 2.89 2.9","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"m7.18 1.77 2.57 2.57 2.57-2.57","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"m18.11 7.55-2.57 2.57","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"m9.75 15.91-2.57 2.57","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"m1.39 12.7 2.57-2.57-2.57-2.58","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]}],
}
