import {IconType} from "../iconType";

export const ShipmentInternationalRegular: IconType = {
    name: 'shipment-international',
    key: 'ShipmentInternational',
    type: 'regular',
    width: 24,
    height: 24,
    viewBox: '0 0 24 24',
    svgPathData: [{"name":"path","attributes":{"d":"M7.54 21.75h-.79a1.5 1.5 0 0 1-1.5-1.5v-6a1.5 1.5 0 0 1 1.5-1.5h9a1.5 1.5 0 0 1 1.5 1.5v5.29","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M17.25 14.25h3a3 3 0 0 1 3 3v3a1.5 1.5 0 0 1-1.5 1.5h-2.29","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"circle","attributes":{"cx":"17.63","cy":"21.38","r":"1.88","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"circle","attributes":{"cx":"9.38","cy":"21.38","r":"1.88","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M15.79 21.75h-4.58","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M23.25 17.25h-3","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M1.76 13.89a9 9 0 1 1 16.99-4.14","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M9.75.75a11.86 11.86 0 0 0-3.75 9","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M9.75.75a11.86 11.86 0 0 1 3.75 9","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]},{"name":"path","attributes":{"d":"M1.26 6.75h16.97","fill":"none","stroke":"currentColor","stroke-linecap":"round","stroke-linejoin":"round","stroke-width":"1.5"},"children":[]}],
}
